### ISSUE TITLE
Added dataset-serialize in section XML/JSON/YAML

### ISSUE THREAD

**Issue by viniciussanchez** [Fr0sT-Brutal/awesome-pascal#102]
This component is a JSON serializer for the DataSet component of Delphi. Allows you to convert JSON to DataSet, DataSet to JSON, validate JSON, and export and load the structure of DataSet fields in JSON format.

https://github.com/viniciussanchez/dataset-serialize

**Comment by Fr0sT-Brutal** [comment]
Added, thanks
