### ISSUE TITLE
New Grid

### ISSUE THREAD

**Issue by Makhaon** [Fr0sT-Brutal/awesome-pascal#120]
[SMDBGrid component](http://www.scalabium.com/smdbgrid.htm). `[Delphi]` The successor TDBGrid with the extended features. Is able to display multiline wordwrap column titles, checkboxs for boolean fields, a convenient select of records from the keyboard and mouse via checkboxs, extanded Indicator column, fixing of columns, an opportunity to exclude insert and delete of records in the DBGrid, own standard PopupMenu, save/restore of a column states, processing of additional events etc. Multilanguage resources.

**Comment by Fr0sT-Brutal** [comment]
Thanks! Added, sorry for delay
