### ISSUE TITLE
please fix description for the QuickLib, more great keywords (and functionality :)

### ISSUE THREAD

**Issue by Makhaon** [Fr0sT-Brutal/awesome-pascal#121]
Quick development library (AutoMapper, LinQ, IOC Dependency Injection, MemoryCache, Scheduled tasks, Config, Serializers, etc) with crossplatform support for Delphi/Firemonkey (Windows,Linux,OSX/IOS/Android) and freepascal (Windows/Linux)

**Comment by Fr0sT-Brutal** [comment]
Thanks! Done, sorry for delay
