### ISSUE TITLE
Please add Apus Game Engine

### ISSUE THREAD

**Issue by Cooler2** [Fr0sT-Brutal/awesome-pascal#125]
[Apus Game Engine](https://github.com/Cooler2/ApusGameEngine). `[Delphi]` `[FPC]` Cross-platform library for making mostly 2D games, GUI applications and web services. Supports UI, text rendering, on-fly localization, particles, basic scripting and many lower level subsystems. Uses OpenGL/GLES and DirectX.

**Comment by Fr0sT-Brutal** [comment]
Added, thanks!
