### ISSUE TITLE
DarkGlass broken link

### ISSUE THREAD

**Issue by dslutej** [Fr0sT-Brutal/awesome-pascal#132]
https://github.com/chapmanworld/DarkGlass

![image](https://user-images.githubusercontent.com/22919263/88328866-5ca6a600-cd29-11ea-8243-ef3c80a3a185.png)

**Comment by dslutej** [comment]
Maybe https://github.com/kenjones007/DarkGlass ?

**Comment by Fr0sT-Brutal** [comment]
Sure. They changed the repo for some reason. Thanks!
