### ISSUE TITLE
DEC V6.0 has been released officially

### ISSUE THREAD

**Issue by MHumm** [Fr0sT-Brutal/awesome-pascal#141]
Hello,

DEC - Delphi Encryption Compendium which you already list, has a new home:
https://github.com/MHumm/DelphiEncryptionCompendium
and V6.0 was released last Sunday and is available via GetIt since this morning.

Best regards

Markus Humm / Main developer of DEC

**Comment by MHumm** [comment]
Ok, it was thrown out of GetIt again because it contains strong cryptography. It will most likely return as a Lite version not containing any ciphers, but the hashes etc. will be still worth something.

**Comment by Fr0sT-Brutal** [comment]
Hello! Thanks, I'll correct the link

> Ok, it was thrown out of GetIt again because it contains strong cryptography.

OMG, what a formalistic stupidity...

**Comment by MHumm** [comment]
It is in GetIt now as DEC Lite with the ciphers removed. But the hashes alone are a good thing already.

**Comment by MHumm** [comment]
Would you like to update your list now, as there is an official release of DEC V6.0 available now?
Further releases should follow from time to time.
