### ISSUE TITLE
Defunct entry detected

### ISSUE THREAD

**Issue by MHumm** [Fr0sT-Brutal/awesome-pascal#142]
This one:

[Delphi] [FPC] Several cipher algorithms: the 128-bit block ciphers AES and Twofish, the 64-bit block cipher Blowfish, and the stream ciphers Salsa20/XSalsa20/ChaCha and Sosemanuk.

contains a link to here:

https://www.wolfgang-ehrhardt.de/

But since the author died a while ago somebody else took over the domain and the original content is no longer there.

**Comment by Fr0sT-Brutal** [comment]
Thanks, I'll remove these links

**Comment by EMBBlaster** [comment]
@MHumm 
Everything from his site is available here:
https://github.com/chadilukito/www.wolfgang-ehrhardt.de

**Comment by jseling** [comment]
Last capture at waybackmachine 
https://web.archive.org/web/20190731114053/http://www.wolfgang-ehrhardt.de:80/
