### ISSUE TITLE
DEC 6.2 released, please update its entry

### ISSUE THREAD

**Issue by MHumm** [Fr0sT-Brutal/awesome-pascal#149]
You already have DEC listed as crypto library.
May I ask for an update of its entry?

1. [Delphi]` `[FPC] as since 6.1 or so FPC support was improved (I didn't test it personally, but somebody contributed some modifications.
2.  6.x already added SHA224 and WhirlPoolT and 6.2 now added SHA3-224, SHA3-256, SHA3-384 and SHA3-512

**Comment by Fr0sT-Brutal** [comment]
Your PR is merged, thanks!
