### ISSUE TITLE
New modules

### ISSUE THREAD

**Issue by Makhaon** [Fr0sT-Brutal/awesome-pascal#154]
[Delphi object to xml](https://github.com/fabiorubim/delphi-object-to-xml). `[Delphi]` Serialize an object to XML using the JVCL library.
[ObjectDebugger](https://github.com/marcocantu/ObjectDebugger). `[Delphi]` The ObjectDebugger is a run-time Object Inspector for Delphi VCL applications.

**Comment by Fr0sT-Brutal** [comment]
Thanks! Added 2nd one, 1st is just a short sample using another lib
