### ISSUE TITLE
ATTabs should be replaced with ATFlatControls

### ISSUE THREAD

**Issue by LingamYoni** [Fr0sT-Brutal/awesome-pascal#155]
> ATTabs. [Delphi] [FPC] Delphi/Lazarus component for lite tabs. OS independent, fully custom drawn.

https://github.com/Alexey-T/ATTabs --> page not found

ATFlatControls @ https://github.com/Alexey-T/ATFlatControls

**Comment by Fr0sT-Brutal** [comment]
You're right, thanks. That's weird though. I have GH action conf-ed that checks all URLs in the list.

**Comment by Fr0sT-Brutal** [comment]
Fixed with d76251f, fixed URLs autocheck as well
