### ISSUE TITLE
The TForge repository looks abandoned.

### ISSUE THREAD

**Issue by Alekcvp** [Fr0sT-Brutal/awesome-pascal#181]
The TForge repository looks abandoned. There are no files in the main trunk, incomplete sets in other trunks.

**Comment by EMBBlaster** [comment]
See:
https://github.com/ElminsterAU/tforge

**Comment by Fr0sT-Brutal** [comment]
Corrected, thanks!

**Comment by Fr0sT-Brutal** [comment]
> It might also be better to replace the link with https://github.com/sergworks/tforge/tree/porting ?..

It's mentioned in description. Also that branch only has 1 additional commit so is abandoned as well
