### ISSUE TITLE
Tool adding

### ISSUE THREAD

**Issue by Makhaon** [Fr0sT-Brutal/awesome-pascal#83]
Please add a tool:
https://github.com/VilleKrumlinde/delphiunitsizes

**Comment by Fr0sT-Brutal** [comment]
Is there any reason why you ignored issue template?

**Comment by Makhaon** [comment]
No, sorry, I see this feature for first time.

**Comment by Fr0sT-Brutal** [comment]
Hmm okay let's consider it a transitional lag xD
