### ISSUE TITLE
What about stable and/or well-developed projects that just simply don't need updates for a long time?

### ISSUE THREAD

**Issue by BeRo1985** [Fr0sT-Brutal/awesome-pascal#92]
Good list, but here's what bothers me:

> Dead projects (not updated for 3 years or more) are mainly ignored except for those which do not have alive analogs.

What about stable and/or well-developed projects that just simply don't need updates for a long time? (Even no IFDEFs for new newer compiler versions and so on.)

**Comment by edwinyzh** [comment]
Yes, there are quite amount of excellent projects  not listed due to that rule. I think that rule is not reasonable for the Delphi/pascal ecosystem.

**Comment by Fr0sT-Brutal** [comment]
Yep, that sentence was made at the early stages of this list when I thought there are pretty much projects alive. In fact I don't follow this rule strictly and projects without updates for 3-4 years are OK. If you know any good projects with such last update time feel free to recommend them.
